### ISSUE TITLE
File operations on UI thread

### ISSUE THREAD

**Issue by emartynov** [Webtrekk/webtrekk-android-sdk#26]
I enabled strict mode for app and I found that Webtrekk does a lot of file operations on UI thread.

Particular examples:

1. `com.webtrekk.webtrekksdk.Request.TrackingRequestTemporaryStore.queueIsEmpty()` whicg is called when any analytics is tracked
2. `com.webtrekk.webtrekksdk.Request.RequestUrlStore.saveURLsToFile()` which is called from the Activity lifecycle listener

The numbers are not big/expensive but this is potential ANR if file system is really busy.

**Comment by Neno0o** [comment]
We have been working on a new Android SDK, currently in BETA testing, feedback is welcome https://github.com/Webtrekk/webtrekk-android-sdk-BETA

I am closing this issue for now, since this repo won't be supported in the near future, and we are planning to have a migration guide to the new SDK once we release a stable version.
