### ISSUE TITLE
Make contribution easy

### ISSUE THREAD

**Issue by emartynov** [Webtrekk/webtrekk-android-sdk#5]
Hi guys,

I cloned the repo and wanted to contribute, however project import failed because one of plugin declaration missing:

```
Error:Plugin with id 'com.github.dcendents.android-maven' not found.
```

I removed it and then gradle complained about the bintray plugin.

And then, of course, I got some DSL not working.

It would be great if people can just check out the project, import and start contribution!

**Comment by olebahlmann** [comment]
Thanks Eugen, we will get back to you on this shortly.

**Comment by arsen-vartbaronov** [comment]
Hi, @emartynov I have the same issue, when I open WebtrekkSDK project directly, because the desired classpath declaration is in parent project. 

As it is described [here](https://github.com/Webtrekk/webtrekk-android-sdk/blob/master/README.md#getting-started) you should open SDKTest project that includes WebtrekkSDK project as well, so you see them both in Android Studio and can compile and test WebtrekkSDK and SDKTest projects at the same time.

As soon as you open SDKTest project everything should be compiled and run without any problem.

**Comment by emartynov** [comment]
Why not follow intuitive gradle project structure? Check Glide for example https://github.com/bumptech/glide

**Comment by arsen-vartbaronov** [comment]
Thank you for this request. I will look at example you provided. 
As next step I am going to move to Android Studio 3.0 and as part of this process I will consider to change project include scheme, based on example you provided.
